### ISSUE TITLE
How do you label the ground truth plane in the point cloud?

### ISSUE THREAD

**Issue by bzdfzfer** [abner-math/PlaneDetection#14]
Hi,
Thanks for sharing your excellent work! I am trying to compare my approach with yours, but currently stucking at labeling my data with ground truth planes. Could you offer some labeling tools or some suggestions on how to do it? THX a lot!

**Comment by abner-math** [comment]
@bzdfzfer [bzdfzfer](https://github.com/bzdfzfer) You can use the own graphic interface which is bundled in this repository. Once you have opened your point cloud in the graphic interface, press SHIFT + right click to start select an area which represents a plane (or CTRL + right click to deselect an area). Once you have selected all the points, in the menu, go to "Detect -> Planes -> Detect planes" (or something similar, I'm not entirely sure right now the exact tab name in the menu). This will fit a plane to the selected points. Once you have done this to all planes in your point cloud, go to "File -> Export Geometry..." and then you can use the exported *.geo file to compare both techniques.

**Comment by bzdfzfer** [comment]
Thanks for your reply. It really helps a lot!
