### ISSUE TITLE
can't detect plane

### ISSUE THREAD

**Issue by JR9124** [abner-math/PlaneDetection#2]
Hi, thanks for sharing your code. I have tried read point cloud whose format is x y z r g b, and then I clicked Autodetected planes, however, there is no result. I have also tried to modify the load module so that it can load point cloud whose format is x y z nx ny nz, but there is still no result. I debugged the code and found that connectivity of point cloud is not established, could you tell me how to read point cloud whose format is x y z or x y z nx ny nz to successfully detect planes by using the code?

**Comment by abner-math** [comment]
Hello! Yes, you need to create a connectivity graph first. Currently in the UI this is only achievable by estimating the normals first (Go to Plane Detector > Estimate Normals).

Another (less handy) alternative is to modify the code to make it skip the normal estimation process when the point cloud has already normals (your case) and just create the connectivity graph. For that you need a little bit of understanding of this class: https://github.com/abnerrjo/PlaneDetection/blob/master/PointCloudEditor/normalestimatorworker.cpp

Also see this issue for faster normal estimation: https://github.com/abnerrjo/PlaneDetection/issues/1

**Comment by JR9124** [comment]
Thanks for your help and quickly reply!
